#!/bin/sh
#
# Author:   Dimitris Deyannis
# E-mail:   d.deyannis@gmail.com
# Modified: Mon 27 Jan 2025 @ 16:51:33 +0200


# dbus magic
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
  done
  unset f
fi


# power manager
#xfce4-power-manager &

# volume icon
volumeicon &

# NetworkManager applet
nm-applet &

# Bluetooth applet
blueman-applet &

# GR - EN shift
setxkbmap -option "grp:switch,grp:alt_shift_toggle,grp_led:scroll" \
	-layout "us,gr"

# multimedia keys
xbindkeys &

# compositor
picom --config ~/.config/picom/picom.conf -b

# notifications
#/usr/lib/xfce4/notifyd/xfce4-notifyd &

# i3 WM
i3
