" Enable syntax highlighting
syntax on

" Show matching brackets when text indicator is over them
set showmatch

" Ignore case when searching
set ignorecase

" Jump to currently maching search result
set incsearch

" Light background
set background=light
