#!/bin/sh
#
# Author:   Dimitris Deyannis
# E-mail:   d.deyannis@gmail.com
# Modified: Wed 19 Dec 2018

echo -e "\n GPU(s):"

i=0

lspci | grep "VGA" | 
while read -r line
do
	gpu=$(echo "$line" | grep -o '\[[0-9,A-Z,a-z, ]*\]' | 
	    sed 's/\[//g' | sed 's/\]//g')
	pci=$(echo "$line" | grep -o  '^[^:]*')
	echo -e "\t $i. $gpu \t\t [PCI $pci]"
	((i++))
done

echo ""
