#!/bin/sh

i=0

echo -e "\n GPU(s):"

lspci | grep "GeForce" | 
while read -r line
do
	gpu=$(echo "$line" | grep -o '\[[0-9,A-Z,a-z, ]*\]' | sed 's/\[//g' | sed 's/\]//g')
	pci=$(echo "$line" | grep -o  '^[^:]*')
	echo -e "\t $i. $gpu \t\t [PCI $pci]"
	((i++))
done

echo ""
