#!/bin/sh

# Dimitris Deyannis
#
# Executed by startx (run your window manager from here)

# dbus magic
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi


# power manager
xfce4-power-manager &

# volume icon
volumeicon &

# dropox
dropbox &

# NetworkManager icon
nm-applet &

# GR - EN shift
setxkbmap -option "grp:switch,grp:alt_shift_toggle,grp_led:scroll" \
	-layout "us,gr"

# multimedia keys
xbindkeys &

# i3 WM
i3
