#!/bin/sh
#
# Author:   Dimitris Deyannis
# E-mail:   d.deyannis@gmail.com
# Modified: Sat 17 Feb 2024 @ 22:45:14 +0200


# vim as default editor
export VISUAL=vim

# EMACS mode
set -o emacs

# fix ksh & st del key
bind -m '^[[P'='^[[3~'

# minimal command prompt
PS1='\u@\h -> '

# sudo
alias sudo="sudo "

# ls with colors and human readable sizes
alias ls="ls -h --color=auto"

# clean packages
alias pacman-clean="pacman -Rsn $(pacman -Qdtq)"

# update, clean and trim
alias sysup="yay -Syyu; sudo pacman-clean; yes | yay -Scc; sudo fstrim -va"

# pastebin
alias sprunge="curl -F \"sprunge=<-\" http://sprunge.us"

# YouTube to MP3
alias ytd="youtube-dl -x --audio-format mp3 --audio-quality 0  \
            -o '/home/ras/Documents/YTD/%(title)s.%(ext)s'"

# update ksh 
alias kshrc=". ~/.kshrc"

# daemonize a job
alias daemon="daemon"
function daemon {
	(exec "$@" &) > /dev/null 2>&1
}
